experiment_name: log-01-07-SortTrans

model:
  name: "SortTrans"
  input_size: 10
  d_token: 256
  num_heads: 2
  num_layers: 4
  d_ff: 256
  dropout: 0.1
  output_size: 10

training:
  epochs: 100
  batch_size: 128
  learning_rate: 0.001

device: cuda

evaluation:
  eval_batch_size: 64
  eval_enabled: true

data:
  dataset_size: 20000