experiment_name: log-01-05

model:
  input_size: 10
  hidden_size: 1024
  output_size: 10

training:
  epochs: 100
  batch_size: 128
  learning_rate: 0.001

device: cuda

evaluation:
  eval_batch_size: 256
  eval_enabled: true

data:
  dataset_size: 20000